apiVersion: v1
kind: Service
metadata:
  name: medical-appointment-service
spec:
  selector:
    app: medical-appointment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
